### ISSUE TITLE
ember-power-select does not work on ember octane

### ISSUE THREAD

**Issue by frytkost** [cibernox/ember-power-select#1251]
**Ember power select don't work on ember octane**
Steps: 
- ember new -b @ember/octane-app-blueprint
- ember install ember-power-select

`<PowerSelect @options={{this.names}} @onChange={{this.foo}} as |name|>
  {{name}} </PowerSelect>
`

Uncaught (in promise) Error: Assertion Failed: The @layout decorator must be provided a template, received: owner => {
      let result = cache.get(owner);

      if (result === undefined) {
        counters.cacheMiss++;
        let compiler = owner.lookup(TEMPLATE_COMPILER_MAIN);
        result = glimmerFactory.create(compiler, {
          owner
        });
        cache.set(owner, result);
      } else {
        counters.cacheHit++;
      }

      return result;
    }
    at Object.assert (index.js:163)
    at index.js:165
    at decorator.js:59
    at Module.callback (power-select.js:158)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:422)

**Comment by cibernox** [comment]
I've released a patch version that added `@ember-decorators/component` to dependencies. Cna you try again with 3.0.2?

**Comment by frytkost** [comment]
@cibernox, I'm still having the same issue with the version 3.0.2.

**Comment by cibernox** [comment]
Ok, I tried and I discovered that there's something broken in Ember canary. It does work if you downgrade to 3.11. I'll investigate further.

**Comment by cibernox** [comment]
This issue in ember-decorators should fix it: https://github.com/ember-decorators/ember-decorators/pull/451

**Comment by kimroen** [comment]
In trying to upgrade from Ember 3.12.0 to 3.13.2, we are running into this issue.

As far as I can tell the linked issue was resolved in version 6.0.1 of `ember-decorators`.
