### ISSUE TITLE
Need to open dropdown twice to see results of promise in dropdown 

### ISSUE THREAD

**Issue by philipdesmedt** [cibernox/ember-power-select#74]
Hi,

First of all, great library! Very much needed something like this in Ember.

I have a promise array that I want to show in a dropdown, which is fetched in my `afterModel` method (using `this.store.findAll('topic')`). This promise is resolved and stored on a controller field called `allTopics`. When I show these topics as follows:

```
{{#ember-power-select options=allTopics selected=model.topics onchange=(action "setTopics") multiple=true as |topic|}}
    {{topic.name}}
{{/ember-power-select}}
```

I get 'No Results Found' the first time I click on the dropdown. When I click away and click on the select box again, the dropdown appears and shows all my topics. So basically, for some reason the `options` field in `ember-power-select` only resolves to the actual topics after the first click. Is this a bug? Maybe related to `multiple=true`?

This happens on Ember 2.0 with an ember-data (2.0) object coming from Rails AMS.

**Comment by cibernox** [comment]
I thought that this situation was covered but I might be wrong.

You can see the tests here: https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/ember-power-select-test.js#L1855-L1912

Can you spot any difference? If you can create a failing test case I'm sure that the fix should not be complicated.

**Comment by philipdesmedt** [comment]
Can't spot any difference.. except that I use an action method on my controller `onchange=(action "setTopics")`, instead of `onchange=(action (mut foo))`.

To fix this, right now I have to run the following afterRender:
```
Ember.run.schedule('afterRender', this, function() {
  Ember.$('.topic-select .ember-power-select-trigger').click();
});
```

Very ugly unfortunately. I can write a test case for this if I have some time in the weekend. Any other ideas in the meantime? :)

**Comment by cibernox** [comment]
The action is not relevant here, so I might have missed something when you try to open the select while the promise is not resolved, although I have a test case that checks that here: http://www.ember-power-select.com/docs/the-list ("The loading state" section).

The only idea I can give you in the meanwhile (not very good tho) is to pass to the component `disabled=allTopcs.isPending`, but this specific bug is one of the one I hated in ember-select2 and therefore one of the reasons I decided to build this component, so I am extremely motivated to fix it :rage: 

I'll check it this evening at home.

**Comment by cibernox** [comment]
@philipdesmedt I've tried to reproduce the error without success. 

Here I've deployed a small demo: http://www.ember-power-select.com/legacy-demo

Here I have the relevant code.

Route: https://github.com/cibernox/ember-power-select/blob/reproduce_promisearray_bug/tests/dummy/app/routes/legacy-demo.js

Template: https://github.com/cibernox/ember-power-select/blob/reproduce_promisearray_bug/tests/dummy/app/templates/legacy-demo.hbs#L36-L38

Can you see any difference? Feel free to fork and play with it. I'm using mirage with a delay of 3000ms.

**Comment by cibernox** [comment]
Quick update, I've merged this into master

**Comment by maartenparmentier** [comment]
Hi guys, I'm @philipdesmedt colleague.

I'm still seeing this issue even after updating to 0.6.1. Ember en ED on 2.2.

Any progress? I think this is the same problem: #148

**Comment by cibernox** [comment]
My main problem is that I couldn't replicate the bug, and when I asked for one nobody was able to provide one.

I'm sure it has to be a small fix, but as usual with debugging finding where the problem lies is the hard part.

**Comment by philipdesmedt** [comment]
Hmmm yeah - it's hard to replicate it because of our ember-data models etc
(and the whole context in general).

I'll have another look in the weekend.

**Comment by cibernox** [comment]
@philipdesmedt Any update on this? Have you tried 0.7.0?

**Comment by philipdesmedt** [comment]
Just upgraded to 0.7.0 and looks like it's fixed now! At least I haven't seen it on at least 3 or 4 power selects anymore. Great stuff! 

I'll close this one. Thx!
